pipeline {
    agent any

    environment {
        ImageRegistry = 'dmiller36'
        EC2_IP = '3.145.52.15'
        DockerComposeFile = 'docker-compose.yml'
        DotEnvFile = '.env'
        REMOTE_USER = 'ubuntu'
    }

    stages {

        stage("buildImage") {
            steps {
                script {
                    echo "Building Docker Image..."
                    bat "docker build -t ${ImageRegistry}/${JOB_NAME}:${BUILD_NUMBER} docker-project-phpcontactform"
                }
            }
        }

        stage("pushImage") {
            steps {
                script {
                    echo "Pushing Image to DockerHub..."
                    withCredentials([usernamePassword(credentialsId: 'docker-login', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                        bat "echo $PASS | docker login -u $USER --password-stdin"
                        bat "docker push ${ImageRegistry}/${JOB_NAME}:${BUILD_NUMBER}"
                    }
                }
            }
        }

        stage("deployCompose") {
            steps {
                script {
                    echo "Deploying with Docker Compose..."

                    withCredentials([sshUserPrivateKey(credentialsId: 'ec2-key', keyFileVariable: 'KEY_FILE')]) {
                        bat """
                        scp -o StrictHostKeyChecking=no -i "%KEY_FILE%" docker-project-phpcontactform/${DotEnvFile} docker-project-phpcontactform/${DockerComposeFile} ubuntu@${EC2_IP}:/home/ubuntu
                        ssh -o StrictHostKeyChecking=no -i "%KEY_FILE%" ubuntu@${EC2_IP} "docker compose -f /home/ubuntu/${DockerComposeFile} --env-file /home/ubuntu/${DotEnvFile} down"
                        ssh -o StrictHostKeyChecking=no -i "%KEY_FILE%" ubuntu@${EC2_IP} "docker compose -f /home/ubuntu/${DockerComposeFile} --env-file /home/ubuntu/${DotEnvFile} up -d"
                        """
                    }
                }
            }
        }
    }
}
